//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hammock.AssetView.Platinum.Tools.RC.RelayClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hammock.AssetView.Platinum.Tools.RC.RelayClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予期しないエラーが発生しました。.
        /// </summary>
        public static string AnUnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続ID「{0}」へは接続済みです。.
        /// </summary>
        public static string ClientWindow_AlreadyConnected {
            get {
                return ResourceManager.GetString("ClientWindow_AlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続ID「{0}」の接続を終了してもよろしいですか？.
        /// </summary>
        public static string ClientWindow_Are_you_sure_you_want_to_close {
            get {
                return ResourceManager.GetString("ClientWindow_Are_you_sure_you_want_to_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続ID:.
        /// </summary>
        public static string ClientWindow_ConnectIdLabel {
            get {
                return ResourceManager.GetString("ClientWindow_ConnectIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続中.
        /// </summary>
        public static string ClientWindow_Connecting {
            get {
                return ResourceManager.GetString("ClientWindow_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続数:.
        /// </summary>
        public static string ClientWindow_ConnectionCount {
            get {
                return ResourceManager.GetString("ClientWindow_ConnectionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存在しない接続IDです。.
        /// </summary>
        public static string ClientWindow_ConnectionIdDoesNotExists {
            get {
                return ResourceManager.GetString("ClientWindow_ConnectionIdDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続を削除しています。.
        /// </summary>
        public static string ClientWindow_DeletingConnection {
            get {
                return ResourceManager.GetString("ClientWindow_DeletingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 強制終了.
        /// </summary>
        public static string ClientWindow_ForceTerminate {
            get {
                return ResourceManager.GetString("ClientWindow_ForceTerminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クライアント端末ログオンユーザー名.
        /// </summary>
        public static string ClientWindow_GridViewColumn_CilentUser {
            get {
                return ResourceManager.GetString("ClientWindow_GridViewColumn_CilentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クライアント端末ホスト名.
        /// </summary>
        public static string ClientWindow_GridViewColumn_ClientHost {
            get {
                return ResourceManager.GetString("ClientWindow_GridViewColumn_ClientHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続ID.
        /// </summary>
        public static string ClientWindow_GridViewColumn_ConnectionId {
            get {
                return ResourceManager.GetString("ClientWindow_GridViewColumn_ConnectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効期限.
        /// </summary>
        public static string ClientWindow_GridViewColumn_Expiration {
            get {
                return ResourceManager.GetString("ClientWindow_GridViewColumn_Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理端末ホスト名.
        /// </summary>
        public static string ClientWindow_GridViewColumn_ManageHost {
            get {
                return ResourceManager.GetString("ClientWindow_GridViewColumn_ManageHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理端末ログオンユーザー名.
        /// </summary>
        public static string ClientWindow_GridViewColumn_ManageUser {
            get {
                return ResourceManager.GetString("ClientWindow_GridViewColumn_ManageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 状態.
        /// </summary>
        public static string ClientWindow_GridViewColumn_State {
            get {
                return ResourceManager.GetString("ClientWindow_GridViewColumn_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最新表示.
        /// </summary>
        public static string ClientWindow_LatestView {
            get {
                return ResourceManager.GetString("ClientWindow_LatestView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続リスト.
        /// </summary>
        public static string ClientWindow_ListOfConnection {
            get {
                return ResourceManager.GetString("ClientWindow_ListOfConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続開始.
        /// </summary>
        public static string ClientWindow_StartConnection {
            get {
                return ResourceManager.GetString("ClientWindow_StartConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続ID「{0}」は有効期限を過ぎています。.
        /// </summary>
        public static string ClientWindow_TheConnectionIdHasExpired {
            get {
                return ResourceManager.GetString("ClientWindow_TheConnectionIdHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待機中.
        /// </summary>
        public static string ClientWindow_Waiting {
            get {
                return ResourceManager.GetString("ClientWindow_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リモート接続の終了を待機しています。.
        /// </summary>
        public static string ClientWindow_WaitingForEndOfRemoteConnection {
            get {
                return ResourceManager.GetString("ClientWindow_WaitingForEndOfRemoteConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssetView RC RelayClient 接続.
        /// </summary>
        public static string ClientWindow_WindowTitle {
            get {
                return ResourceManager.GetString("ClientWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続リストを取得しています。.
        /// </summary>
        public static string GettingConnectionList {
            get {
                return ResourceManager.GetString("GettingConnectionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「astRC_RelayClient.exe」は既に起動しています。.
        /// </summary>
        public static string HasAlreadyBeenInRunning {
            get {
                return ResourceManager.GetString("HasAlreadyBeenInRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企業ID.
        /// </summary>
        public static string LoginWindow_CompanyId {
            get {
                return ResourceManager.GetString("LoginWindow_CompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssetView RC RelayServiceログイン設定.
        /// </summary>
        public static string LoginWindow_GroupBoxHeader {
            get {
                return ResourceManager.GetString("LoginWindow_GroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード.
        /// </summary>
        public static string LoginWindow_PasswordLabel {
            get {
                return ResourceManager.GetString("LoginWindow_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssetView RC RelayClient ログイン.
        /// </summary>
        public static string LoginWindow_WindowTitle {
            get {
                return ResourceManager.GetString("LoginWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リレーサーバーへの接続に失敗しました。企業ID・パスワードを確認して、再度試行してください。.
        /// </summary>
        public static string LoginWindowViewModelValidator_CanNotConnectRelayServer {
            get {
                return ResourceManager.GetString("LoginWindowViewModelValidator_CanNotConnectRelayServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企業IDを入力してください。.
        /// </summary>
        public static string LoginWindowViewModelValidator_PleaseInputCompanyId {
            get {
                return ResourceManager.GetString("LoginWindowViewModelValidator_PleaseInputCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードを入力してください。.
        /// </summary>
        public static string LoginWindowViewModelValidator_PleaseInputPassword {
            get {
                return ResourceManager.GetString("LoginWindowViewModelValidator_PleaseInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「AssetView RC」のアクティベーションが確認できませんでした。.
        /// </summary>
        public static string NotActivated {
            get {
                return ResourceManager.GetString("NotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssetView RC RelayClient.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リモート接続の待機を終了しています。.
        /// </summary>
        public static string ProgressWindow_WaitingForRemoteConnection {
            get {
                return ResourceManager.GetString("ProgressWindow_WaitingForRemoteConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssetView RC RelayClient 進行状況.
        /// </summary>
        public static string ProgressWindow_WindowTitle {
            get {
                return ResourceManager.GetString("ProgressWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssetView RC RelayClient モード選択.
        /// </summary>
        public static string SelectModeWindowTitle {
            get {
                return ResourceManager.GetString("SelectModeWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続待機を終了してもよろしいですか？.
        /// </summary>
        public static string ServerWindow_AreYouOkToQuitWaiting {
            get {
                return ResourceManager.GetString("ServerWindow_AreYouOkToQuitWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本接続IDは {0} まで有効です。.
        /// </summary>
        public static string ServerWindow_ConnectionIdIsValidUntil {
            get {
                return ResourceManager.GetString("ServerWindow_ConnectionIdIsValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下の接続IDを管理者へお伝えください。.
        /// </summary>
        public static string ServerWindow_PleseTellConnectionIdToManager {
            get {
                return ResourceManager.GetString("ServerWindow_PleseTellConnectionIdToManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssetView RC RelayClient 待機.
        /// </summary>
        public static string ServerWindow_WindowTitle {
            get {
                return ResourceManager.GetString("ServerWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リモートからの接続を受け付ける.
        /// </summary>
        public static string SwitchWindow_AcceptConnection {
            get {
                return ResourceManager.GetString("SwitchWindow_AcceptConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リモートのコンピューターを操作する.
        /// </summary>
        public static string SwitchWindow_OperateRemoteComputer {
            get {
                return ResourceManager.GetString("SwitchWindow_OperateRemoteComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行う操作を選択してください。.
        /// </summary>
        public static string SwitchWindow_PleaseSelectOperation {
            get {
                return ResourceManager.GetString("SwitchWindow_PleaseSelectOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接続数の上限に達したため、セッションを作成できませんでした。.
        /// </summary>
        public static string TooManySessions {
            get {
                return ResourceManager.GetString("TooManySessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クラウドへ接続できませんでした。.
        /// </summary>
        public static string UnableToConnectToTheCloud {
            get {
                return ResourceManager.GetString("UnableToConnectToTheCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to リモート接続の待機を開始しています。.
        /// </summary>
        public static string WaitingForRemoteConnection {
            get {
                return ResourceManager.GetString("WaitingForRemoteConnection", resourceCulture);
            }
        }
    }
}
